[package]
name = "asdfspline"
version = "0.0.0"
authors = ["Matthias Geier <Matthias.Geier@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

publish = false

[workspace]
members = ["ffi"]

[dependencies]
superslice = "1"
thiserror = "1.0"
nalgebra = "0.31"
