name: Run Tests
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUST_LOG: info
  PYTEST_ADDOPTS: "--color=yes"
jobs:
  rust-lib:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Clone Git repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run Rust tests
        run: |
          cargo test --workspace --all-features

  ffi-python:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install cbindgen
        run: |
          cargo install cbindgen
      - name: Clone Git repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Double-check Python version
        run: |
          python --version
          python -m pip --version
      - name: Install Python dependencies
        run: |
          python -m pip install nbconvert ipykernel matplotlib
          python -m pip install pytest
      - name: Install Python package
        working-directory: python
        run: |
          python -m pip install -e .
      - name: Upload asdfspline.h header file
        uses: actions/upload-artifact@v3
        with:
          name: header-file-${{ matrix.os }}
          path: |
            python/asdfspline.h
      - name: Run Python tests
        working-directory: python
        run: |
          python -m pytest
      - name: Execute notebooks
        working-directory: python/examples
        run: |
          python -m nbconvert --execute --to html *.ipynb
      - name: Upload converted notebooks
        uses: actions/upload-artifact@v3
        with:
          name: notebooks-${{ matrix.os }}
          path: |
            python/examples/*.html

  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Git repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: rustfmt
        run: |
          cargo fmt --all --check
      - name: clippy
        run: |
          cargo clippy --all-targets --all-features -- -D warnings
      - name: Build docs
        run: |
          cargo rustdoc --all-features -- -D warnings

  msrv:
    strategy:
      matrix:
        rust-version: ["1.61.0"]
    runs-on: ubuntu-latest
    steps:
      - name: Clone Git repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Rust version ${{ matrix.rust-version }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-version }}
      - name: Check whether it compiles
        run: |
          cargo check --all-features --verbose
